import type { Metadata } from "next";
// import { Providers } from "./providers";

import localFont from "next/font/local";

import "./globals.css";

const minecraft = localFont({ src: "../../public/fonts/Minecraftia-Regular.ttf" });

export const metadata: Metadata = {
	title: "Sebastian's Website",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
